FileVersion = 1

[Project]
Name = "glm-beef"
TargetType = "BeefLib"
StartupObject = "glm_beef.Program"

[Configs.Debug.Win64]
BuildKind = "StaticLib"
BeefLibType = "Static"

[Configs.Release.Win64]
BuildKind = "StaticLib"
